# Generated by Django 3.1.1 on 2020-10-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('confirmpassword', models.CharField(max_length=120)),
                ('present_address', models.TextField(blank=True, max_length=120, null=True)),
                ('permanent_address', models.TextField(blank=True, max_length=120, null=True)),
                ('job', models.CharField(blank=True, max_length=120, null=True)),
                ('profilepicture', models.ImageField(upload_to='profilepic')),
                ('coverpicture', models.ImageField(upload_to='timelinecoverpic')),
            ],
        ),
        migrations.CreateModel(
            name='timelinephotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('profile_pic', models.ImageField(upload_to='photos/timelinepic')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userpic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=10000)),
                ('caption', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeline_pic', models.ImageField(upload_to='timelinepic')),
                ('profile_pic', models.ImageField(upload_to='timelineprofilepic')),
                ('cover_pic', models.ImageField(upload_to='timelinecoverpic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='profilephotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('profile_pic', models.ImageField(upload_to='photos/profilepic')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userpic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='friendrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('contact', models.TextField(max_length=11)),
                ('email', models.EmailField(max_length=120)),
                ('user', models.ManyToManyField(to='UserProfile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='coverphotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('cover_pic', models.ImageField(upload_to='photos/timelinecoverpic')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userpic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.profile')),
            ],
        ),
    ]
